### ISSUE TITLE
Proposal of CONTRIBUTING.md and Navbar Updates

### ISSUE THREAD

**Issue by namansinghrana** [kevrom0215/profile#23]
### Summary
I would like to propose adding a `CONTRIBUTING.md` file to help guide new contributors on how to contribute to the project. Additionally, I suggest updating the navbar to improve user experience and engagement.

### Reasons for Proposal
- **CONTRIBUTING.md**: 
  - Having a `CONTRIBUTING.md` file will provide clear guidelines on how to contribute, coding standards, and best practices. This can help new contributors understand the process better and encourage more contributions.
- **Navbar Update**:
  - The current navbar could be updated to enhance user experience. Some suggestions for improvement:
    - Adding links to documentation.
    - Improving the layout for better accessibility.

### Next Steps
If this proposal is accepted, I can work on creating the `CONTRIBUTING.md` file and implement the navbar updates. I would appreciate any feedback on this idea.

**Comment by kevrom0215** [comment]
Hi @namansinghrana,
Thank you for your inputs and suggestions! I’m currently using this GitHub repository just for GitHub Pages and am still learning the React framework.

For the navbar, I plan to remove it and simplify the layout to make the page linear. This project doesn’t have a specific plan yet—it's more of a playground for me to experiment.

That said, if you have any further suggestions or ideas to share, I’ll happily consider them!

Thanks again for your interest! 😊
